on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu VM

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4
    # Step 4: Build the Docker image
    - name: Build Docker image
      run: docker build . -t saighantasala/app:latest
    - name: login to docker
      run: docker login -u saighantasala -p ${{secrets.SAIGHANTASALA}}
    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push saighantasala/app:latest
        
        